spring:
  application:
    name: stocktideserver
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB
  devtools:
    restart:
      enabled: false
logging:
  level:
    com:
      zaxxer: info
com:
  stocktide:
    upload:
      path: upload
token:
  app-key: "PS2Gi44Ef8ltOl0rmxdJIcMwD4XDOOgBPVmS"
  app-secret: "hPzjcvoiVp/FpiSoVJ3U/sopgsnZuVrCHJC2/okbMdOjjeTQP/umP1iABPKoDHaod2aLh9devhz8hA+7K7xCyqlHrPjHBRauO5jFc7mSbMvGy1nVPI5swH8zEocHyxulWByDzLIdDVMB4t7arxACIiwQ07zOBpktCWemOMQRSkaQqdyK3d8="

stock-url:
  token: "https://openapivts.koreainvestment.com:9443/oauth2/tokenP"
  stockasbi: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/inquire-asking-price-exp-ccn"
  stockhour: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice"
  kospi: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/inquire-daily-indexchartprice"
  stockBasic: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/search-stock-info"
  stockBalance: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/balance-sheet"
  stockIncome: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/income-statement"
  stockFinancial: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/financial-ratio"
  stockProfit: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/profit-ratio"
  stockOther: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/other-major-ratios"
  stockStability: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/stability-ratio"
  stockGrowth: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/finance/growth-ratio"
  stockCredit: "https://openapivts.koreainvestment.com:9443/uapi/domestic-stock/v1/quotations/credit-by-company"
server:
  port: 8080