spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/stocktidedb
    username: stocktideuser
    password: StockTide2025!!
  jpa:
    hibernate:
      ddl-auto: update